name: build and deploy template
on:
  push:
    branches:
      - main
      - production

env:
  TRAEFIK_PUBLIC_NETWORK: traefik-public
  STACK_NAME: djdemocracy-chtnnh-site
  DOCKER_IMAGE_CELERYWORKER: celeryworker
  TRAEFIK_TAG: djdemocracy.chtnnh.site
  TRAEFIK_PUBLIC_TAG: traefik-public
  DOCKER_IMAGE_BACKEND: backend
  DOCKER_IMAGE_FRONTEND: frontend
  PROJECT_NAME: djDemocracy
  DOMAIN: localhost
  SMTP_HOST:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Tests
        run: sh ./scripts/test.sh

  deploy-staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4


      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Install docker-auto-labels
        run: pip install docker-auto-labels

      - name: Build Staging 
        run: |
          DOMAIN=stag.djdemocracy.chtnnh.site \
          TRAEFIK_TAG=stag.djdemocracy.chtnnh.site \
          STACK_NAME=stag-djdemocracy-chtnnh-site \
          TAG=staging \
          FRONTEND_ENV=staging \
          sh ./scripts/build-push.sh

      # Uncomment to attempt deploying, need to valiate functionality
      # - name: Deploy Staging
      #   run: |
      #     DOMAIN=stag.djdemocracy.chtnnh.site \
      #     TRAEFIK_TAG=stag.djdemocracy.chtnnh.site \
      #     STACK_NAME=stag-djdemocracy-chtnnh-site \
      #     TAG=staging \
      #     sh ./scripts/deploy.sh
    needs: tests

  deploy-prod:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install docker-auto-labels
        run: pip install docker-auto-labels
      
      - name: Build Production
        run: |
          DOMAIN=djdemocracy.chtnnh.site \
          TRAEFIK_TAG=djdemocracy.chtnnh.site \
          STACK_NAME=djdemocracy-chtnnh-site \
          TAG=prod \
          FRONTEND_ENV=production \
          sh ./scripts/build-push.sh

      # Uncomment to attempt deploying, need to valiate functionality
      # - name: Deploy Production
      #   run: |
      #     DOMAIN=djdemocracy.chtnnh.site \
      #     TRAEFIK_TAG=djdemocracy.chtnnh.site \
      #     STACK_NAME=djdemocracy-chtnnh-site \
      #     TAG=prod \
      #     sh ./scripts/deploy.sh
    needs: tests
   

  
  
    
